name: Android Debug APK

on:
  workflow_dispatch:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install SDKMAN & Gradle 8.7
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.7
          gradle --version

      - name: Generate Gradle Wrapper (8.7)
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          gradle wrapper --gradle-version 8.7
          ./gradlew --version
          
      - name: Kotlin compile (diagnostic)
        run: ./gradlew clean :app:compileDebugKotlin --no-daemon --stacktrace --info


      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
